### ISSUE TITLE
Support Centos 7

### ISSUE THREAD

**Issue by chris-rock** [hardening-io/chef-os-hardening#79]
Fix: pam_passwdqc handling

**Comment by johnbellone** [comment]
:+1:

**Comment by ovaistariq** [comment]
+1

**Comment by ovaistariq** [comment]
The installation of packages can be disabled by setting the following attribute:
```
default['auth']['pam']['passwdqc']['enable'] = false
```

However, a proper fix involves setting up /etc/security/pwquality.conf

**Comment by chris-rock** [comment]
thanks @ovaistariq for mentioning this. If you are faster with adding a patch for CentOS 7, a PR is welcome.

**Comment by boldandbusted** [comment]
FYI, this is covered by https://github.com/hardening-io/chef-os-hardening/pull/104 :).

**Comment by chris-rock** [comment]
Thanks @boldandbusted for this addition
