### ISSUE TITLE
1.3.0 release on supermarket is broken

### ISSUE THREAD

**Issue by paulczar** [hardening-io/chef-os-hardening#83]
Get an error when doing a 'berks upload' that includes the new 1.3.0 from supermarket.

turns out in the packaged released ( but not in the source ) there's a file `os-hardening/templates/.DS_Store` which chef server doesn't know how to handle and flips out.  setting `Berksfile` to pull it from git repo at tag `v1.3.0` works fine.

**Comment by chris-rock** [comment]
Hi @paulczar Thanks for reporting. I deleted all .DS_Store files and republished to supermarket. Let me know if you have further issues.
