### ISSUE TITLE
Archlinux doesn't have a limits.d directory by default

### ISSUE THREAD

**Issue by evaryont** [hardening-io/chef-os-hardening#84]
`/etc/security/limits.d` doesn't exist by default. It works and is included when it does exist, but needs to be made before https://github.com/hardening-io/chef-os-hardening/blob/master/recipes/limits.rb#L21 is ran. A simple wrapper recipe works:

```ruby
directory '/etc/security/limits.d' do
  owner 'root'
  group 'root'
  mode '0755'
end
include_recipe 'os-hardening::default'
```

**Comment by Rockstar04** [comment]
Looks like a fix for this was merged in, you can point Berkshelf to master if you would like to use these changes until we tag a new release.
